version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: my-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: boxoffice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Добавляем монтирование каталога initdb
    command: ["postgres", "-c", "max_connections=300"]

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-webapp
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: boxoffice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
      build:
        context: ./nginx
      container_name: my-nginx
      ports:
        - "80:8080"
        - "443:4430"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - webapp
